### ISSUE TITLE
Add option for hiding in tray + start/stop with P3D

### ISSUE THREAD

**Issue by Berzerker** [shotwn/FS-Time-Sync#2]
Hello. Thank you for this wonderful tool, it does indeed work fantastically. I still have 2 "issues" I'd potentially like to see addressed:

1. The tool stops working once P3D is closed, even if it's reopened. I need to close and restart the tool for it to start back up. An option to auto-start and stop with P3D would greatly enhance the usability of the tool, IMO.

2. An option to hide to tray the tool so that it's basically in a "black box" mode (with live sync auto-enabled), requiring basically no user interaction. The LRM (landing rate monitor) client handles this well.

**Comment by shotwn** [comment]
Thank you for your feedback. You want to run it and forget it at background as far as I get. So when you run the sim it will sync real time automagically.

I will try to add these after adding offsets feature.
- [ ] Gracefully reconnect FSUIPC
- [ ] Hide UI and run in background.
- [ ] Create a tray icon.

**Comment by Berzerker** [comment]
Yessir! That's it. thanks again for your help, I look forward to any future enhancements

**Comment by shotwn** [comment]
[Release 0.1.2](https://github.com/shotwn/FS-Time-Sync/releases/tag/v0.1.2-alpha) must cover the features you need.

Check settings to enable startup features which you have requested.

I didn't have much of a testing process but everything seems to be working fine.

Enjoy !

**Comment by Berzerker** [comment]
Thank you! I tested this earlier today and it seems to work very well. Thank you again.

**Comment by shotwn** [comment]
I am glad and you are welcome. Closing this issue now.
